---
- name: Install Master Nodes.
  hosts: master
  gather_facts: true
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: kubeadm.yaml setup file.
      shell: |
            cat >> kubeadm.yaml << EOF
            apiVersion: kubeadm.k8s.io/v1beta2
            kind: InitConfiguration
            nodeRegistration:
              kubeletExtraArgs:
                  node-ip: "{{ hostvars[groups['master'][0]]['ansible_host'] }},{{ hostvars[groups['master'][0]].ansible_all_ipv6_addresses[0] }}"
            ---
            apiVersion: kubeadm.k8s.io/v1beta2
            kind: ClusterConfiguration
            featureGates:
              IPv6DualStack: true
            networking:
              podSubnet: 200.200.0.0/16,fd7a:cccc:dddd::/48
              serviceSubnet: 10.200.0.0/16,fd00:0002:0:0:1::/108
            EOF
            exit 0

    - name: Set up kubeadm
      shell: kubeadm init --config kubeadm.yaml

    - name: Set up kubectl root
      shell: mkdir -p $HOME/.kube && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config
      args:
        warn: no

    - name: Set up kubectl ubuntu
      become: yes
      become_method: sudo
      become_user: ubuntu
      shell: mkdir -p $HOME/.kube && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config
      args:
        warn: no

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      become: no
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
