---
- name: Ping test Reaktion on All Nodes.
  hosts: worker
  gather_facts: false
  tasks:
    - name: Test Ping time.
      local_action: shell ping -c 4 {{ inventory_hostname }}
      ignore_errors: true
      register: result
      changed_when: false
    - debug:
        msg: "{{ result['stdout_lines'] }}"
